services:
# Remove the postgres service from the compose file by deleting these lines
  # postgres:
  #   image: postgres
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 30s
  #     timeout: 10s
  #   restart: always
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  tracking-server:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
      # We don't need to include the depends_on key anymore
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    ports:
      # MLflow UI is available at http://localhost:5050
      - "5050:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-postgresql-sfo3-tanyasharma-do-user-17404056-0.j.db.ondigitalocean.com:25060/${POSTGRES_DB}?sslmode=require
      --default-artifact-root s3://mlflow-bucket-tanyasharma 
      --serve-artifacts
      --gunicorn-opts "--log-level debug"
# We don't need to persist a volume anymore
# volumes:
#   postgres_data: { }